### ISSUE TITLE
'union sigval' 与arm-none-eabi编译器中存在命名冲突

### ISSUE THREAD

**Issue by Tsan1024** [Firmament-Autopilot/FMT-Firmware#123]
/data/arm-gcc-toolchain/arm-none-eabi/include/sys/signal.h:42:7: error: redefinition of 'union sigval'
 union sigval {
       ^~~~~~
In file included from /data/cpuls/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21:0,
                 from /data/cpuls/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /data/cpuls/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /data/cpuls/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /data/cpuls/FMT-Firmware/src/firmament.h:25,
                 from /data/cpuls/FMT-Firmware/src/module/toml/toml.c:28:
/data/cpuls/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:28:7: note: originally defined here
 union sigval

**Comment by JcZou** [comment]
输入scons -c清理一下工程，然后再编译

**Comment by Tsan1024** [comment]
解决了

**Comment by Tsan1024** [comment]
> 输入scons -c清理一下工程，然后再编译

有效
