### ISSUE TITLE
Problems of SD driver

### ISSUE THREAD

**Issue by kiku-LYXQ** [Firmament-Autopilot/FMT-Firmware#129]
The implementation in target/pixhawk/fmu-v2/drivers/sdio/drv_sdio.c is rt_err_t drv_sdio_init(const char* device_name), but in target/pixhawk/fmu-v2/drivers/sdio/drv_sdio.h and the implementation in board.c, it is declared and implemented as rt_err_t drv_sdio_init(void). So when I click drv_sdio_init , a funtion, of board.c in fmu-v2, it will go to definition of drv_sdio.c in fmu-v5.

**Comment by JcZou** [comment]
Yes, I've noticed this. This issue will be fixed soon, thanks!
