### ISSUE TITLE
fmu-v5编译不成功

### ISSUE THREAD

**Issue by bingobinlw** [Firmament-Autopilot/FMT-Firmware#15]
linux：ubuntu 20.04 
工具链：gcc-arm-none-eabi-7-2018-q2-update
代码版本：v0.2.1

编译fmu-v2版与io固件没问题，但是编译fmu-v5固件时会出现如下报错

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build/fmt/src/module/toml/toml.o
In file included from /opt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/signal.h:6:0,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:72,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /home/bingo/project/FMT-Firmware/src/include/firmament.h:23,
                 from /home/bingo/project/FMT-Firmware/src/module/toml/toml.c:28:
/opt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/sys/signal.h:42:7: error: redefinition of 'union sigval'
 union sigval {
       ^~~~~~
In file included from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21:0,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /home/bingo/project/FMT-Firmware/src/include/firmament.h:23,
                 from /home/bingo/project/FMT-Firmware/src/module/toml/toml.c:28:
/home/bingo/project/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:28:7: note: originally defined here
 union sigval
       ^~~~~~
In file included from /opt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/signal.h:6:0,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:72,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /home/bingo/project/FMT-Firmware/src/include/firmament.h:23,
                 from /home/bingo/project/FMT-Firmware/src/module/toml/toml.c:28:
/opt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/sys/signal.h:47:8: error: redefinition of 'struct sigevent'
 struct sigevent {
        ^~~~~~~~
In file included from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21:0,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /home/bingo/project/FMT-Firmware/src/include/firmament.h:23,
                 from /home/bingo/project/FMT-Firmware/src/module/toml/toml.c:28:
/home/bingo/project/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:36:8: note: originally defined here
 struct sigevent
        ^~~~~~~~
In file included from /opt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/signal.h:6:0,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:72,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /home/bingo/project/FMT-Firmware/src/include/firmament.h:23,
                 from /home/bingo/project/FMT-Firmware/src/module/toml/toml.c:28:
/opt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/sys/signal.h:72:3: error: conflicting types for 'siginfo_t'
 } siginfo_t;
   ^~~~~~~~~
In file included from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtlibc.h:21:0,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtdef.h:1104,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/include/rtthread.h:24,
                 from /home/bingo/project/FMT-Firmware/rtos/rt-thread/components/drivers/include/rtdevice.h:15,
                 from /home/bingo/project/FMT-Firmware/src/include/firmament.h:23,
                 from /home/bingo/project/FMT-Firmware/src/module/toml/toml.c:28:
/home/bingo/project/FMT-Firmware/rtos/rt-thread/include/libc/libc_signal.h:55:24: note: previous declaration of 'siginfo_t' was here
 typedef struct siginfo siginfo_t;
                        ^~~~~~~~~
CC build/fmt/src/task/fmtio/task_fmtio.o
CC build/fmt/src/task/logger/task_logger.o
CC build/fmt/src/task/status/task_status.o
CC build/fmt/src/task/vehicle/multicopter/task_vehicle.o
scons: *** [build/fmt/src/module/toml/toml.o] Error 1
scons: building terminated because of errors.

**Comment by JcZou** [comment]
编译前先输入一下`scons -c`清理一下工程再尝试重新编译

**Comment by bingobinlw** [comment]
问题解决了，`scons -c` 清理一下工程后成功编译。
