### ISSUE TITLE
不是一个 issue.

### ISSUE THREAD

**Issue by wenzhicode** [Firmament-Autopilot/FMT-Firmware#9]
"基于模型设计提供更高效的开发体验以及更轻松的调试方式 " ，一直很向往MBD的开发方式，但平时工作没有使用过这种方式。
主要是自己能力上欠缺，另一方面是目前调试的硬件还不能支持MBD方式，芯片flash不够，也没有足够的引脚来接个SD卡，用来记录日志，平时调试都是用很多时间来换取一般效果。（用PIX4板子是可以的，但工作上用不上）

希望MBD方式发扬光大，在飞控这一块大放异彩。FMT是一个里程碑。

**Comment by JcZou** [comment]
确实，如果没有SD卡记录日志，会失去开环仿真这个很强大的功能。但是如果记录的数据量不大，频率也不太高的情况下，可以通过增加缓存的大小来增加写入Flash的吞吐量，或许可以满足日志记录的要求。
但是即使不做开环仿真，MBD也是可以像传统开发模式那样，只不过算法是使用像Simulink这种工具进行图形化的方式进行开发，也是可以轻松获得更高的开发和调试效率。（最近在开发FMS的功能，相比于用C/C++来写状态机逻辑，使用Simulink的State Flow实现状态机逻辑真的是太高效了）
最后，感谢支持，FMT要走的路还很长，希望可以跟MBD相互成就。

**Comment by wenzhicode** [comment]
好的。我需要的是把MBD用起来，能用多少都是一种进步。
